baseURL = 'https://trantannguyenblog.netlify.app/'
languageCode = 'vi-vn'
title = 'Portfolio'
theme = 'pehtheme-hugo'

[pagination]
pagerSize = 6

summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
	mainSections = 'posts'

	[params.author]
		name = 'Anthony Arphan'
		bio = 'Debitis assumenda esse dignissimos aperiam delectus maxime tenetur repudiandae dolore'
		avatar = '/images/nasa-astronaut-unsplash.jpg'
		twitter = 'https://twitter.com/insertapps'

[menu]
	[[menu.main]]
		name = 'Trang chủ'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Giới thiệu'
		pageRef = '/about'
		weight = 15

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts]
    source = 'assets'
    target = 'static'
